// THIS MODULE ONLY CONTAINS EVENT HANDLERS
import $ from "jquery";
import cuid from "cuid";
import api from "./api";
import events from "./events";
import index from "./index";
import store from "./store";
import templates from "./templates";

const handleNewButtonClick = function () {
  $("main").on("click", ".new", function () {
    // code that you want to execute
    console.log("new item button clicked");
    // when user clicks button, change adding state to true
    store.STORE.adding = true;
    // when user clicks button, change filtering state to false
    store.STORE.filtering = false;
    // render new html for the form when adding state is true
    index.render();
  });
};

const handleFilterClick = function () {
  $("main").on("click", ".filter", function () {
    // console log to indicate user clicked the button
    console.log("filter button clicked");
    // when user clicks button, change addings state to false
    store.STORE.adding = false;
    // when user clicks button, change filtering state to true
    store.STORE.filtering = true;
    // render new html for the filter dropdown when filtering state is true
    index.render();
  });
};

const handleFilterDropdown = function () {
  $("main").on("change", ".ratings", function () {
    //code that you want to excute
    console.log("user selected filter");
    store.STORE.filter = $(".ratings option:selected").val();
    console.log(`the rating is ${store.STORE.filter}`);
    // hide all bookmarks that are less than this rating / show bookmarks that are equal or greater than this rating using the STORE data
    //render the html
    index.render();
  });
};

const handleDeleteItemClick = function () {
  $("main").on("click", ".delete", function () {
    //console log that user clicked button
    console.log("user clicked delete button");
    event.preventDefault();
    // change the state of the STORE
    store.STORE.adding === false;
    store.STORE.filtering === false;
    store.STORE.error === null;
    // // create a variable that is assigned to the data of the id gerenreate by the cuid
    const DeleteId = $(this).attr("data-clicked-id");
    console.log(DeleteId);
    store.deleteBookmarkObject(DeleteId);
    console.log(store.STORE.bookmarks);
    api.deleteBookmarkAPI(DeleteId);
    // when user clicks delete button, use splice to remove specific bookmark from STORE
    // create a function that removes that id from the bookmarks array
    // call the gnereateBookmarkString() and then
    templates.generateBookmarksString();
    index.render();
  });
};

const handleClearFilterClick = function () {
  $("main").on("click", ".clear-filter", function () {
    console.log("clear filter button clicked");
    // change filtering state in STORE to false
    store.STORE.adding = false;
    store.STORE.filtering = false;
    store.STORE.filter = 0;
    // if filtering state is false generate html without dropdown box/home state of app
    index.render();
  });
};

const handleBookmarkClick = function () {
  // create on click event for the individual titles of the bookmarks
  $("main").on("click", ".item-title", function () {
    event.preventDefault();
    console.log("expand bookmark clicked");
    //change the state of the STORE
    store.STORE.adding === false;
    store.STORE.filtering === false;
    store.STORE.error === null;
    // create a variable that is assisgned to the data of the id generated by the cuid
    const clickedId = $(this).attr("data-clicked-id");
    console.log(clickedId);
    store.expandBookmarkToggle(clickedId);
    templates.generateBookmarksString();
    index.render();
    // console log that user clicked button
    // for that item change expanded in STORE to true
    // render new html for expanded bookmark
    // render();
  });
};

const handleCancelClick = function () {
  $("main").on("click", ".cancel", function () {
    // code that you want to execute
    console.log("cancel button clicked");
    // when user clicks button, change adding state to false
    store.STORE.adding = false;
    // when user clicks button, change filtering state to false
    store.STORE.filtering = false;
    // render the home page html based on the condition
    store.STORE.error = null;
    index.render();
  });
};

const handleCreateItemClick = function () {
  //the purpose of this function is to capture the values from the input form to be able to use for the factory function
  $("main").on("click", ".create", function () {
    store.STORE.error = null;
    event.preventDefault();
    console.log("create bookmark button clicked");
    event.preventDefault();
    event.preventDefault();
    console.log("form submitted");
    store.formErrorState();
    store.STORE.adding = false;
    store.STORE.filtering = false;
    console.log(store.STORE.error);
    console.log(store.STORE.adding);
    store.addNewBookmark(); // this fucntion will call addNewBookmark() as well as createBookmarkObject()

    // when the user inputs information into the form, capture the info in way that can be added into the STORE
    // use .val to capture the input values and set to values to pass into factory function
    // call the addNewBookmark function to add bookmark and change the state of the STORE
  });
};

function eventHandlers() {
  handleNewButtonClick();
  handleFilterClick();
  handleFilterDropdown();
  handleDeleteItemClick();
  handleClearFilterClick();
  handleBookmarkClick();
  handleCancelClick();
  handleCreateItemClick();
}

export default {
  eventHandlers,
};
